### ISSUE TITLE
Some issues in Firefox

### ISSUE THREAD

**Issue by CMDR-Sloma** [aukedejong/lovelace-windrose-card#51]
I am getting error in my Home Assistant while using Firefox:

```
Logger: frontend.js.latest.202401040
Source: components/system_log/__init__.py:300
First occurred: 21:12:57 (1 occurrences)
Last logged: 21:12:57

Uncaught error from Firefox 121.0 on Windows 10 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "windrose-card" has already been used with this registry 87659/</window.CustomElementRegistry.prototype.define (src/scoped-custom-element-registry.js:44:14) e/</< (/hacsfiles/lovelace-windrose-card/windrose-card.js:54:60) e/< (/hacsfiles/lovelace-windrose-card/windrose-card.js:54:75) __decorate (/hacsfiles/lovelace-windrose-card/windrose-card.js:19:95) /hacsfiles/lovelace-windrose-card/windrose-card.js:2224:16
```

Not sure what is exactly the reason for this error. The card seems to be working fine despite the error.

**Comment by ildar170975** [comment]
Could be related to how you installed the card.

**Comment by aukedejong** [comment]
Is the problem fixed?    If so, I will close this issue.

**Comment by CMDR-Sloma** [comment]
Nope, I am still getting error in the logs.

Also, I installed the card through HACS.

**Comment by aukedejong** [comment]
I released a new version.
Any changes?

**Comment by fishter** [comment]
This also occurs in Android 11 Chrome, so it's not confined to Firefox.

`
Error: Failed to execute 'define' on 'CustomElementRegistry': the name "windrose-card" has already been used with this registry window.CustomElementRegistry.define (src/scoped-custom-element-registry.js:44:14) /hacsfiles/lovelace-windrose-card/windrose-card.js:43:632 /hacsfiles/lovelace-windrose-card/windrose-card.js:43:647 t (/hacsfiles/lovelace-windrose-card/windrose-card.js:1:250) /hacsfiles/lovelace-windrose-card/windrose-card.js:43:577
`

**Comment by aukedejong** [comment]
Released version 1.13.0
I updated and cleaned up the library's the card uses.

Please let me know of this fixes the issue?

**Comment by gonzalo1059** [comment]
I'm still having this problem both in Firefox and Chrome Android
